sudo: false
language: python
cache: pip
matrix:
    include:
        # - python: 2.6
        # - python: 2.7
        # - python: 3.3
        # - python: 3.4
        # - python: 3.5
        # - python: 3.6
        # - "pypy"
        - language: generic  # osx + python2
          os: osx
          before_install:
            - brew update
            - brew unlink python
            - brew install python
            - virtualenv env -p python
            - source env/bin/activate
        - language: generic  # osx + python3
          os: osx
          before_install:
            - brew update
            - brew unlink python3
            - brew install python3
            - virtualenv env -p python3
            - source env/bin/activate
install: |
    if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
        pip install -U ipaddress unittest2 argparse mock==1.0.1
    elif [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then
        pip install -U ipaddress mock
    elif [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then
        pip install -U ipaddress
    fi
    pip install --upgrade coverage coveralls setuptools flake8
script:
    - ./.ci/travis/run.sh
after_success:
    - |
        if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]] && [[ "$(uname -s)" != 'Darwin' ]]; then
            echo "sending test coverage results to coveralls.io"
            coveralls
        fi
