sudo: false
language: python
cache: pip
matrix:
    include:
        - python: 2.6
        - python: 2.7
        - python: 3.3
        - python: 3.4
        - python: 3.5
        - python: 3.6
        - "pypy"
        - language: generic
          os: osx
          env: PYVER=py27
        - language: generic
          os: osx
          env: PYVER=py34
install:
    - ./.ci/travis/install.sh
script:
    - ./.ci/travis/run.sh
after_success:
    # upload test reports to coveralls.io
    - |
        if [ "$(uname -s)" != 'Darwin' ]; then
            coveralls
        fi
